export const AUTH_LOGGED_IN_YES = 'AUTH_LOGGED_IN_YES';
export const AUTH_LOGGED_IN_NO = 'AUTH_LOGGED_IN_NO';

export const AUTH_LOGGED_OUT_YES = 'AUTH_LOGGED_OUT_YES';
export const AUTH_LOGGED_OUT_NO = 'AUTH_LOGGED_OUT_NO';

export const AUTH_AUTHENTICATION_STATUS_YES = 'AUTH_AUTHENTICATION_STATUS_YES';
export const AUTH_AUTHENTICATION_STATUS_NO = 'AUTH_AUTHENTICATION_STATUS_NO';

export const AUTH_SIGNUP_EMAIL_EXISTS_YES = 'AUTH_SIGNUP_EMAIL_EXISTS_YES';
export const AUTH_SIGNUP_EMAIL_EXISTS_NO = 'AUTH_SIGNUP_EMAIL_EXISTS_NO';

export const AUTH_SIGNUP_SUCCESS_YES = 'AUTH_SIGNUP_SUCCESS_YES';
export const AUTH_SIGNUP_SUCCESS_NO = 'AUTH_SIGNUP_SUCCESS_NO';

export const AUTH_SIGNUP_CONFIRMATION_TOKEN_YES = 'AUTH_SIGNUP_CONFIRMATION_TOKEN_YES';
export const AUTH_SIGNUP_CONFIRMATION_TOKEN_NO = 'AUTH_SIGNUP_CONFIRMATION_TOKEN_NO';

export const AUTH_FORGOT_PASSWORD_SEND_YES = 'AUTH_FORGOT_PASSWORD_SEND_YES';
export const AUTH_FORGOT_PASSWORD_SEND_NO = 'AUTH_FORGOT_PASSWORD_SEND_NO';

export const AUTH_RESET_PASSWORD_TOKEN_YES = 'AUTH_RESET_PASSWORD_TOKEN_YES';
export const AUTH_RESET_PASSWORD_TOKEN_NO = 'AUTH_RESET_PASSWORD_TOKEN_NO';

export const AUTH_RESET_PASSWORD_SUCCESS_YES = 'AUTH_RESET_PASSWORD_SUCCESS_YES';
export const AUTH_RESET_PASSWORD_SUCCESS_NO = 'AUTH_RESET_PASSWORD_SUCCESS_NO';

export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';


export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";